const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const rules=require('../tools/station-rules.cjs');
const html=fs.readFileSync('cloudbase-dist/index.html','utf8'),code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1].replace(/\nboot\(\);\s*$/,'\n');
function client(){const storage=new Map();const c=vm.createContext({console,Date,Map,Set,URL,URLSearchParams,setTimeout,clearTimeout,alert(){},document:{getElementById:()=>({style:{},querySelectorAll:()=>[]}),querySelectorAll:()=>[]},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});vm.runInContext(code,c);c.run=s=>vm.runInContext(s,c);c.run(`today=()=> '2026-09-27';render=()=>{};state={stations:[{id:'x',currentSituation:'base'}],stationUndoHistory:{},stationRedoHistory:{}};cloudSync.ready=true;cloudSync.syncedState=clone(state);queueCloudSync=()=>{};saveLocalOnly();`);return c}
const c=client();
c.run(`recordStationUndo(state.stations[0],'first');state.stations[0].currentSituation='first';save();recordStationUndo(state.stations[0],'second');state.stations[0].currentSituation='second';save();restoreStationHistory('x');`);assert.equal(c.run('state.stations[0].currentSituation'),'first');c.run(`restoreStationHistory('x');`);assert.equal(c.run('state.stations[0].currentSituation'),'base');c.run(`restoreStationHistory('x','redo');`);assert.equal(c.run('state.stations[0].currentSituation'),'first');
c.run(`state.stations[0].currentSituation='later remote change';saveLocalOnly();`);const before=c.run('JSON.stringify(state)');assert.throws(()=>c.run(`restoreStationHistory('x')`),/其他修改/);assert.equal(c.run('JSON.stringify(state)'),before);
const legacy=client();legacy.run(`state.stationUndoHistory.x=[{snapshot:{id:'x',currentSituation:'old'}}];saveLocalOnly()`);assert.throws(()=>legacy.run(`restoreStationHistory('x')`),/旧记录/);
const invalid=client();invalid.run(`recordStationUndo(state.stations[0],'future');state.stations[0].completeDate='2026-10-01';`);assert.throws(()=>invalid.run('save()'),/不能晚于/);assert.equal(invalid.run('state.stations[0].completeDate'),undefined);assert.equal(invalid.run('cloudSync.dirty'),false);
const station={id:'x',establishRef:'old',selectionDone:true,establishDate:'2026-09-01',entryDate:'2026-09-02'};
for(const patch of [{pourDate:'2026-10-01'},{pourDate:'2026-09-01'},{establishRef:'new'},{id:'hijack'},{'__proto__.polluted':true}])assert.throws(()=>rules.applyRemoteStationPatch(station,{patch},'2026-09-27'));
assert.equal(rules.applyRemoteStationPatch(station,{patch:{pourDate:'2026-09-03'}},'2026-09-27').pourDate,'2026-09-03');assert.equal(station.pourDate,undefined);
const goodClose={establishRef:'',establishDate:'',entryDate:'',priorProjectHistory:[{...station}]};assert.equal(rules.applyRemoteStationPatch(station,{patch:goodClose},'2026-09-27').establishRef,'');
const workflow=fs.readFileSync('.github/workflows/apply-cloudbase-updates.yml','utf8');assert.ok(workflow.includes('station=applyRemoteStationPatch(before,cmd,'));assert.ok(workflow.includes('expectedAfter:clone(station)'));
console.log('PASS shared remote/browser validation, immutable rejected patches, guarded undo/redo, legacy history refusal, invalid-save rollback, workflow shared-rule wiring');
