const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{const browser=await chromium.launch({channel:'chrome',args:['--no-proxy-server']});const folder='audit-evidence/layout-'+Date.now();fs.mkdirSync(folder,{recursive:true});try{for(const width of [1440,768,390,320]){const page=await browser.newPage({viewport:{width,height:900},hasTouch:width<721});let writes=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/')&&r.method()!=='GET'){const body=r.postDataJSON();if(!(r.url().endsWith('/api/db')&&body.operation==='select'))writes++}});await page.goto(process.env.CHECK_URL||'http://127.0.0.1:8787');await page.locator('#password').fill(JSON.parse(fs.readFileSync('cloudflare/secrets.local.json')).APP_PASSWORD);await page.getByRole('button',{name:'进入工作台'}).click();await page.waitForFunction(()=>cloudSync.ready);
if(width<721){assert(await page.locator('.top').evaluate(e=>e.offsetHeight)<120);assert(!await page.locator('#globalSearch').isVisible());await page.locator('#toggleSearch').click();assert(await page.locator('#globalSearch').isVisible());assert.equal(await page.locator('#toggleSearch').getAttribute('aria-expanded'),'true');await page.locator('#toggleSearch').click()}
await page.screenshot({path:path.join(folder,width+'-home.png')});
for(const pool of ['selection','difficult','pending','building','complete']){await page.locator('[data-page="'+pool+'"]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(folder,width+'-'+pool+'.png')});if(pool==='complete'){const expected=await page.evaluate(()=>state.stations.filter(isComplete).map(s=>s.completeDate||'完工日期待补'));for(const text of expected)assert((await page.locator('.module-list').innerText()).includes(text))}
await page.locator('.module-list [data-open]').first().click();assert(await page.locator('.base-details').getAttribute('open')!==null);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await page.locator('#editBaseBtn').count(),1);
if(width<721)assert(await page.locator('#app>.panel').nth(1).evaluate(e=>e.getBoundingClientRect().top)<800);
if(pool==='building'){assert.equal(await page.locator('.construction-issue').count(),1);await page.locator('.construction-issue>summary').click();assert(await page.locator('#toggleConstructionProblem').isVisible());await page.locator('.construction-issue>summary').click()}
await page.screenshot({path:path.join(folder,width+'-'+pool+'-detail.png')});await page.locator('#editBaseBtn').click();assert(await page.locator('#baseEdit').isVisible());await page.locator('#cancelBase').click();assert(!await page.locator('#baseEdit').isVisible());await page.locator('#backBtn').click()}
assert.equal(writes,0,'layout inspection must not write business data');assert.deepEqual(errors,[]);console.log('PASS '+width+'px: navigation/search, five modules/details, base edit, issue disclosure, completion dates, no overflow or business writes');await page.close()}}finally{await browser.close()}console.log('Evidence '+folder)})().catch(e=>{console.error(e);process.exitCode=1});
