// Mutations are restricted to local D1.
const fs=require('fs'),path=require('path'),assert=require('assert/strict');const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{async function open(width){const p=await b.newPage({viewport:{width,height:800}});await p.goto('http://127.0.0.1:8787');await p.locator('#password').fill(JSON.parse(fs.readFileSync('cloudflare/secrets.local.json')).APP_PASSWORD);await p.getByRole('button',{name:'进入工作台'}).click();await p.waitForFunction(()=>typeof cloudSync!=='undefined'&&cloudSync.ready);return p}const p=await open(1440),q=await open(390);const ids=await p.evaluate(()=>Object.fromEntries(['pending','building','complete'].map(m=>[m,state.stations.find(s=>stationModule(s)===m&&(m!=='building'||s.establishDate))?.id])));
async function go(id){await p.evaluate(id=>go('station/'+id),id);await p.locator('#backBtn').waitFor()}
async function draft(selector,value){await p.locator(selector).fill(value);await p.locator(selector).blur();for(const force of [false,true]){await p.evaluate(async force=>{cloudSync.metaRevision-=1;await cloudRefresh(force)},force);assert.equal(await p.locator(selector).inputValue(),value)}await p.evaluate(()=>render());}
await go(ids.pending);await p.locator('#pendingEstablishInput').waitFor();await draft('#pendingEstablishInput','待立项草稿保护');await draft('#maintProjectCode','LOCAL-DRAFT');await go(ids.building);await p.locator('#nodeDate').waitFor();await draft('#nodeDate','2026-09-25');await go(ids.complete);await p.locator('#completeDateInput').waitFor();await draft('#completeDateInput','2026-09-25');
await go(ids.pending);await p.locator('#maintReturnProblem').waitFor();p.once('dialog',d=>d.accept('本地验证退回原因'));await p.locator('#maintReturnProblem').click();await p.waitForFunction(()=>!cloudSync.dirty&&!cloudSync.syncing&&!cloudSync.lastError);await q.evaluate(()=>cloudRefresh(true));assert.equal(await q.evaluate(id=>stationModule(stationBy(id)),ids.pending),'difficult');assert.equal(await q.evaluate(id=>latestProblemFollowup(stationBy(id)),ids.pending),'本地验证退回原因');
await p.evaluate(id=>applyStationCommand(stationBy(id),'SELECTION_DONE'),ids.pending);await p.waitForFunction(()=>!cloudSync.dirty&&!cloudSync.syncing);await p.evaluate(()=>render());p.once('dialog',d=>d.accept('本地验证重新选址'));await p.locator('#maintReturnSelection').click();await p.waitForFunction(()=>!cloudSync.dirty&&!cloudSync.syncing&&!cloudSync.lastError);await q.evaluate(()=>cloudRefresh(true));assert.equal(await q.evaluate(id=>stationModule(stationBy(id)),ids.pending),'selection');
await go(ids.complete);await p.locator('#completeDateInput').waitFor();const counts=await p.evaluate(()=>cloudModuleCounts(state));await p.locator('#completeDateInput').fill(await p.evaluate(()=>today()));await p.locator('#saveCompleteDate').click();await p.waitForFunction(()=>!cloudSync.dirty&&!cloudSync.syncing&&!cloudSync.lastError);assert.deepEqual(await p.evaluate(()=>cloudModuleCounts(state)),counts);await q.evaluate(()=>cloudRefresh(true));assert.equal(await q.evaluate(id=>stationBy(id).completeDate,ids.complete),await p.evaluate(()=>today()));await q.reload();await q.waitForFunction(()=>typeof cloudSync!=='undefined'&&cloudSync.ready);assert.equal(await q.evaluate(id=>stationModule(stationBy(id)),ids.complete),'complete');
console.log('PASS blurred pending/project/node/completion drafts survive automatic and manual refresh; both return paths sync across independent sessions; complete date persists with unchanged module counts');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
