const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('cloudbase-dist/index.html','utf8');
const code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1].replace(/\nboot\(\);\s*$/,'\n');
const els={},alerts=[];let saves=0,confirms=0,allow=true;
const c=vm.createContext({console,Date,Map,Set,URL,URLSearchParams,document:{getElementById:id=>els[id]||null,querySelectorAll:()=>[]},alert:x=>alerts.push(x),confirm:()=>{confirms++;return allow},history:{},saveSpy:()=>saves++});
vm.runInContext(code,c);const run=s=>vm.runInContext(s,c);
run(`today=()=> '2026-09-27';recordStationUndo=()=>{};save=saveSpy;toast=()=>{};renderStation=()=>{};var st={id:'isolated',establishRef:'code',establishDate:'2026-09-01',entryDate:'2026-09-11',pourDate:'2026-09-15'};`);
assert.equal(run('scheduleMeta(st).nodeOverdue'),false);assert.ok(run('scheduleMeta(st).historicalDelay.includes("进场")'));
assert.equal(run('scheduleMeta({...st,pourDate:""}).nodeOverdue'),true);
assert.equal(run('mainStage({...st,towerDate:"2026-09-26"})'),'装塔完成，待引电、配套');
assert.equal(run('scheduleMeta({...st,towerDate:"2026-09-26"}).earlyTower'),true);
assert.equal(run('mainStage({...st,towerDate:"2026-09-26",powerDate:"2026-09-26",supportDate:"2026-09-26"})'),'专业已完成，待整站确认');
assert.equal(run('pendingEstablishMeta({pendingEstablishProgress:"赔补已解决，待立项"}).label'),'待立项');
assert.equal(run('pendingEstablishMeta({pendingEstablishStatus:"待规划",pendingEstablishProgress:"赔补已解决"}).label'),'待规划');
assert.ok(run('validateActualDate("2026-09-28")'));assert.ok(run('validateActualDate("2026-02-30")'));assert.equal(run('validateActualDate("2026-09-27")'),'');
assert.ok(run('validateNodeDate(st,"pourDate","2026-09-05")'));assert.ok(run('validateNodeDate(st,"entryDate","2026-09-20")'));
els.saveNode={};els.nodeSel={value:'completeDate'};els.nodeDate={value:'2026-10-01'};run('bindConstruction(st)');els.saveNode.onclick();assert.equal(saves,0);assert.equal(run('isComplete(st)'),false);
els.nodeDate.value='2026-09-27';allow=false;els.saveNode.onclick();assert.equal(saves,0);assert.equal(confirms,1);
allow=true;els.saveNode.onclick();assert.equal(saves,1);assert.equal(run('isComplete(st)'),true);
run(`var pending={id:'pending',selectionDone:true};`);assert.throws(()=>run(`applyStationCommand(pending,'START_PROJECT',{code:'new',date:'2026-10-01'})`));assert.equal(run('pending.establishRef'),undefined);
run(`applyStationCommand(pending,'START_PROJECT',{code:'new',date:'2026-09-27'})`);assert.equal(run('stationModule(pending)'),'building');assert.throws(()=>run(`applyStationCommand(pending,'START_PROJECT',{code:'overwrite'})`));
run(`var difficult={id:'difficult',isDifficultSite:true,selectionProblemStatus:'未解决'};applyStationCommand(difficult,'SELECTION_DONE')`);assert.equal(run('stationModule(difficult)'),'pending');assert.equal(run('difficult.isDifficultSite'),false);
console.log('PASS status regression: historical/current delays, actual stage, explicit pending status, date/chronology validation, completion confirmation, guarded transitions');

run(`var back={id:'back',selectionDone:true,pendingEstablishStatus:'待协调',pendingEstablishProgress:'旧立项情况',priorProjectHistory:[{establishRef:'old'}]};applyStationCommand(back,'RETURN_SELECTION',{reason:'场址需重新协调',problem:true});`);
assert.equal(run('stationModule(back)'),'difficult');assert.equal(run('needsFocus(back)'),true);assert.equal(run('back.priorProjectHistory[0].establishRef'),'old');assert.equal(run('latestProblemFollowup(back)'),'场址需重新协调');
run(`applyStationCommand(back,'SELECTION_DONE');applyStationCommand(back,'RETURN_SELECTION',{reason:'重新选址'});`);assert.equal(run('stationModule(back)'),'selection');assert.equal(run('back.pendingEstablishProgress'),'');
assert.throws(()=>run(`applyStationCommand(back,'RETURN_SELECTION',{reason:'重复退回'})`));
run(`var done={id:'done',completeConfirmed:true};applyStationCommand(done,'UPDATE_COMPLETE_DATE',{date:'2026-09-26'});`);assert.equal(run('stationModule(done)'),'complete');assert.equal(run('done.completeDate'),'2026-09-26');assert.throws(()=>run(`applyStationCommand(done,'UPDATE_COMPLETE_DATE',{date:'2026-09-28'})`));assert.equal(run('done.completeDate'),'2026-09-26');
console.log('PASS pending return paths, retained project history, fresh follow-up, completion date without reopening and invalid-date rejection');

run("today=()=> '2026-10-07';var early={id:'early',selectionDone:true,establishRef:'',establishDate:'',entryDate:'',pourDate:''};applyStationCommand(early,'START_BEFORE_ESTABLISHMENT',{progress:'截至10月6日桩基完成浇筑；未立项，编码后补',pourConfirmed:true});");
assert.equal(run('stationModule(early)'),'building');assert.equal(run('hasProjectCode(early)'),false);assert.equal(run('mainStage(early)'),'已浇筑，日期待补');assert.equal(run('early.pourDate'),'');assert.equal(run('early.establishDate'),'');assert.equal(run('buildDay(early)'),null);assert.equal(run('cureEnd(early)'),'');assert.ok(run('row(early,"after").includes("未立项 · 编码后补")'));assert.ok(run('constructionHtml(early).includes("已完成，日期待补")'));
run("early.entryDate='2026-10-01';applyStationCommand(early,'START_PROJECT',{code:'TEST-CODE',date:'2026-10-07'});");assert.equal(run('early.entryDate'),'2026-10-01');assert.equal(run('early.pourConfirmed'),true);assert.equal(run('mainStage(early)'),'已浇筑，日期待补');assert.equal(run('ruleNodeError(early,"establishDate","2026-10-07","2026-10-07")'),'');assert.ok(run('ruleNodeError({...early,constructionBeforeEstablishment:false},"establishDate","2026-10-07","2026-10-07")'));
assert.throws(()=>run("applyStationCommand(early,'START_PROJECT',{code:'OTHER'})"));
run("applyStationCommand(early,'CLOSE_PROJECT',{remark:'本地测试归档'});");assert.equal(run('stationModule(early)'),'pending');assert.equal(run('early.pourConfirmed'),false);assert.equal(run('early.constructionStarted'),false);assert.equal(run('early.priorProjectHistory.at(-1).pourConfirmed'),true);assert.equal(run('early.priorProjectHistory.at(-1).constructionBeforeEstablishment'),true);
console.log('PASS pre-establishment construction: undated pour, no fake code/date/deadline, later establishment retains facts, scoped chronology exception and archived flags');
