const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('cloudbase-dist/index.html','utf8');
const code=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1].replace(/\nboot\(\);\s*$/,'\n');
const els={},alerts=[];let saves=0,confirms=0,allow=true;
const c=vm.createContext({console,Date,Map,Set,URL,URLSearchParams,document:{getElementById:id=>els[id]||null,querySelectorAll:()=>[]},alert:x=>alerts.push(x),confirm:()=>{confirms++;return allow},history:{},saveSpy:()=>saves++});
vm.runInContext(code,c);const run=s=>vm.runInContext(s,c);
run(`today=()=> '2026-09-27';recordStationUndo=()=>{};save=saveSpy;toast=()=>{};renderStation=()=>{};var st={id:'isolated',establishRef:'code',establishDate:'2026-09-01',entryDate:'2026-09-10',pourDate:'2026-09-15'};`);
assert.equal(run('scheduleMeta(st).nodeOverdue'),false);assert.ok(run('scheduleMeta(st).historicalDelay.includes("进场")'));
assert.equal(run('scheduleMeta({...st,pourDate:""}).nodeOverdue'),true);
// Pouring uses five calendar days after entry; the deadline itself is not overdue.
run(`var pourCase={establishRef:'code',establishDate:'2026-09-20',entryDate:'2026-09-22'};`);
assert.equal(run('scheduleMeta(pourCase).pourDue'),'2026-09-27');
assert.equal(run('scheduleMeta(pourCase).nodeOverdue'),false);
assert.equal(run('scheduleMeta({...pourCase,entryDate:"2026-09-21"}).nodeOverdue'),true);
assert.ok(run('scheduleMeta({...pourCase,entryDate:"2026-09-21"}).reason.includes("进场后5天")'));
assert.equal(run('nodeDeadlineMeta({...pourCase,pourDate:"2026-09-27"}).historicalDelay'),'');
assert.ok(run('nodeDeadlineMeta({...pourCase,pourDate:"2026-09-28"}).historicalDelay.includes("进场后5天 1天")'));
assert.equal(run('scheduleMeta({...pourCase,establishRef:""}).pourDue'),'2026-09-27');
assert.equal(run('mainStage({...st,towerDate:"2026-09-26"})'),'装塔完成，待引电、配套');
assert.equal(run('scheduleMeta({...st,towerDate:"2026-09-26"}).earlyTower'),true);
assert.equal(run('mainStage({...st,towerDate:"2026-09-26",powerDate:"2026-09-26",supportDate:"2026-09-26"})'),'专业已完成，待整站确认');
assert.equal(run('pendingEstablishMeta({pendingEstablishProgress:"赔补已解决，待立项"}).label'),'待立项');
assert.equal(run('pendingEstablishMeta({pendingEstablishStatus:"待规划",pendingEstablishProgress:"赔补已解决"}).label'),'待规划');
assert.ok(run('validateActualDate("2026-09-28")'));assert.ok(run('validateActualDate("2026-02-30")'));assert.equal(run('validateActualDate("2026-09-27")'),'');
assert.ok(run('validateNodeDate(st,"pourDate","2026-09-05")'));assert.ok(run('validateNodeDate(st,"entryDate","2026-09-20")'));
els.saveNode={};els.nodeSel={value:'completeDate'};els.nodeDate={value:'2026-10-01'};run('bindConstruction(st)');els.saveNode.onclick();assert.equal(saves,0);assert.equal(run('isComplete(st)'),false);
els.nodeDate.value='2026-09-27';allow=false;els.saveNode.onclick();assert.equal(saves,0);assert.equal(confirms,1);
allow=true;els.saveNode.onclick();assert.equal(saves,1);assert.equal(run('isComplete(st)'),true);
run(`var pending={id:'pending',selectionDone:true};`);assert.throws(()=>run(`applyStationCommand(pending,'START_PROJECT',{code:'new',date:'2026-10-01'})`));assert.equal(run('pending.establishRef'),undefined);
run(`applyStationCommand(pending,'START_PROJECT',{code:'new',date:'2026-09-27'})`);assert.equal(run('stationModule(pending)'),'building');assert.throws(()=>run(`applyStationCommand(pending,'START_PROJECT',{code:'overwrite'})`));
run(`var difficult={id:'difficult',isDifficultSite:true,selectionProblemStatus:'未解决'};applyStationCommand(difficult,'SELECTION_DONE')`);assert.equal(run('stationModule(difficult)'),'pending');assert.equal(run('difficult.isDifficultSite'),false);
console.log('PASS status regression: historical/current delays, actual stage, explicit pending status, date/chronology validation, completion confirmation, guarded transitions');
